#!/usr/bin/env python3
"""Render the Codex-authored PR attribution sentence from rollout history."""

from __future__ import annotations

import argparse
from collections import Counter, deque
from dataclasses import dataclass
import datetime as dt
import json
import os
from pathlib import Path
import re
from typing import Dict, Iterable, Iterator, List, Mapping, Optional, Sequence, Tuple
import uuid


FALLBACK_LABEL = "GPT-5.6 Sol Ultra"
SENTENCE = "This PR is purely generated by LLM: OpenAI Codex ({})."
MAX_RECORD_BYTES = 16 * 1024 * 1024
TIMESTAMP_KEYS = ("timestamp", "ts", "time", "created_at", "updated_at")
UUID_RE = re.compile(
    r"[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-"
    r"[0-9a-fA-F]{4}-[0-9a-fA-F]{12}"
)
MODEL_LABELS = {
    "gpt-5.6-sol": "GPT-5.6 Sol",
}
EFFORT_LABELS = {
    "low": "Low",
    "medium": "Medium",
    "high": "High",
    "xhigh": "Extra High",
    "max": "Max",
    "ultra": "Ultra",
}
Pair = Tuple[str, str]
TurnKey = Tuple[str, str]


class RolloutError(RuntimeError):
    """The selected task family cannot supply complete attribution evidence."""


@dataclass(frozen=True)
class Vote:
    pair: Pair
    turn_order: Optional[int]
    timestamp: Optional[dt.datetime]
    sequence: int


def parse_instant(value: str) -> dt.datetime:
    text = value.strip()
    if text.endswith("Z"):
        text = text[:-1] + "+00:00"
    try:
        parsed = dt.datetime.fromisoformat(text)
    except ValueError as exc:
        raise argparse.ArgumentTypeError(
            "expected an RFC3339 timestamp, for example 2026-08-11T12:00:00Z"
        ) from exc
    if parsed.tzinfo is None:
        parsed = parsed.replace(tzinfo=dt.timezone.utc)
    return parsed.astimezone(dt.timezone.utc)


def normalize_session_id(value: str) -> str:
    if UUID_RE.fullmatch(value):
        return value.lower()
    return value


def turn_order(turn_id: str) -> Optional[int]:
    try:
        parsed = uuid.UUID(turn_id)
    except ValueError:
        return None
    if parsed.version != 7:
        return None
    return parsed.int >> 80


def iter_records(path: Path) -> Iterator[Mapping[str, object]]:
    try:
        handle = path.open("rb")
    except OSError as exc:
        raise RolloutError("unable to read a selected rollout") from exc
    with handle:
        while True:
            raw_line = handle.readline(MAX_RECORD_BYTES + 1)
            if not raw_line:
                return
            if len(raw_line) > MAX_RECORD_BYTES:
                while raw_line and not raw_line.endswith(b"\n"):
                    raw_line = handle.readline(MAX_RECORD_BYTES + 1)
                raise RolloutError("a selected rollout record exceeds 16 MiB")
            try:
                row = json.loads(raw_line)
            except (UnicodeError, ValueError) as exc:
                raise RolloutError("a selected rollout record is malformed") from exc
            if not isinstance(row, dict):
                raise RolloutError("a selected rollout record is not an object")
            yield row


def inventory_rollouts(codex_home: Path) -> Dict[str, List[Path]]:
    by_session: Dict[str, List[Path]] = {}

    def inventory_error(error: OSError) -> None:
        raise RolloutError("unable to inventory a rollout tree") from error

    for root_name in ("sessions", "archived_sessions"):
        root = codex_home / root_name
        if not root.is_dir():
            continue
        for directory, subdirectories, filenames in os.walk(
            root,
            followlinks=False,
            onerror=inventory_error,
        ):
            subdirectories.sort()
            for filename in sorted(filenames):
                if not filename.startswith("rollout-") or not filename.endswith(".jsonl"):
                    continue
                if any(not character.isprintable() for character in filename):
                    continue
                path = Path(directory) / filename
                if path.is_symlink():
                    continue
                for match in UUID_RE.finditer(filename):
                    session_id = match.group(0).lower()
                    by_session.setdefault(session_id, []).append(path)
    return by_session


def record_timestamp(row: Mapping[str, object]) -> Optional[dt.datetime]:
    payload = row.get("payload")
    containers = (row, payload) if isinstance(payload, dict) else (row,)
    for container in containers:
        for key in TIMESTAMP_KEYS:
            value = container.get(key)
            if not isinstance(value, str):
                continue
            try:
                return parse_instant(value)
            except argparse.ArgumentTypeError:
                continue
    return None


def resolve_root_session_id(
    rollout_paths: Mapping[str, Sequence[Path]],
    selected_session_id: str,
) -> str:
    roots = set()
    for path in rollout_paths.get(selected_session_id, ()):
        for row in iter_records(path):
            if row.get("type") != "session_meta":
                continue
            payload = row.get("payload")
            if not isinstance(payload, dict):
                raise RolloutError("a session metadata record has an invalid payload")
            lifecycle_id = payload.get("id")
            root_session_id = payload.get("session_id")
            if not isinstance(lifecycle_id, str) or not isinstance(root_session_id, str):
                continue
            if normalize_session_id(lifecycle_id) == selected_session_id:
                roots.add(normalize_session_id(root_session_id))
    if len(roots) > 1:
        raise RolloutError("selected rollout names multiple root task IDs")
    root_session_id = next(iter(roots), selected_session_id)
    if root_session_id not in rollout_paths:
        raise RolloutError("root task rollout is unavailable")
    return root_session_id


def vote_order(vote: Vote) -> Tuple[int, dt.datetime, int]:
    timestamp = vote.timestamp or dt.datetime.min.replace(tzinfo=dt.timezone.utc)
    return (vote.timestamp is not None, timestamp, vote.sequence)


def collect_turn_votes(
    rollout_paths: Mapping[str, Sequence[Path]],
    root_session_id: str,
) -> Dict[TurnKey, Vote]:
    root_session_id = normalize_session_id(root_session_id)
    pending = deque([root_session_id])
    visited = set()
    turns: Dict[TurnKey, Vote] = {}
    sequence = 0

    while pending:
        session_id = pending.popleft()
        if session_id in visited:
            continue
        visited.add(session_id)
        for path in rollout_paths.get(session_id, ()):
            for row in iter_records(path):
                sequence += 1
                payload = row.get("payload")
                record_type = row.get("type")
                if record_type in {
                    "session_meta",
                    "event_msg",
                    "turn_context",
                } and not isinstance(payload, dict):
                    raise RolloutError("a selected rollout record has an invalid payload")
                if not isinstance(payload, dict):
                    continue
                if (
                    record_type == "event_msg"
                    and payload.get("type") == "sub_agent_activity"
                ):
                    child_id = payload.get("agent_thread_id")
                    if not isinstance(child_id, str) or not child_id:
                        raise RolloutError("a subagent activity record has no task ID")
                    child_id = normalize_session_id(child_id)
                    if child_id not in rollout_paths:
                        raise RolloutError("a referenced subagent rollout is unavailable")
                    if child_id not in visited:
                        pending.append(child_id)
                if record_type != "turn_context":
                    continue
                turn_id = payload.get("turn_id")
                model = payload.get("model")
                effort = payload.get("effort")
                if not isinstance(turn_id, str) or not turn_id:
                    raise RolloutError("a turn context has no turn ID")
                if not all(isinstance(value, str) and value for value in (model, effort)):
                    continue
                timestamp = record_timestamp(row)
                vote = Vote((model, effort), turn_order(turn_id), timestamp, sequence)
                key = (session_id, turn_id)
                previous = turns.get(key)
                if previous is None or vote_order(vote) > vote_order(previous):
                    turns[key] = vote
    return turns


def choose_pair(turns: Iterable[Vote]) -> Optional[Pair]:
    votes = list(turns)
    if not votes:
        return None
    counts = Counter(vote.pair for vote in votes)
    majority = max(counts.values())
    candidates = {pair for pair, count in counts.items() if count == majority}
    if len(candidates) == 1:
        return next(iter(candidates))
    tied_votes = [vote for vote in votes if vote.pair in candidates]
    if any(vote.turn_order is None for vote in tied_votes):
        return None
    latest_turn_order = max(vote.turn_order for vote in tied_votes)
    latest_pairs = {
        vote.pair for vote in tied_votes if vote.turn_order == latest_turn_order
    }
    if len(latest_pairs) != 1:
        return None
    return next(iter(latest_pairs))


def label_for_pair(pair: Optional[Pair]) -> str:
    if pair is None:
        return FALLBACK_LABEL
    model, effort = pair
    model_label = MODEL_LABELS.get(model)
    effort_label = EFFORT_LABELS.get(effort)
    if model_label is None or effort_label is None:
        return FALLBACK_LABEL
    return "{} {}".format(model_label, effort_label)


def render_sentence(
    codex_home: Path,
    session_id: Optional[str],
) -> str:
    if not session_id:
        return SENTENCE.format(FALLBACK_LABEL)
    try:
        rollouts = inventory_rollouts(codex_home)
        selected_session_id = normalize_session_id(session_id)
        if selected_session_id not in rollouts:
            return SENTENCE.format(FALLBACK_LABEL)
        root_session_id = resolve_root_session_id(rollouts, selected_session_id)
        turns = collect_turn_votes(rollouts, root_session_id)
    except RolloutError:
        return SENTENCE.format(FALLBACK_LABEL)
    return SENTENCE.format(label_for_pair(choose_pair(turns.values())))


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Render the Codex-authored PR attribution sentence."
    )
    parser.add_argument(
        "--session-id",
        help="Task ID to resolve to its Desktop root; defaults to CODEX_THREAD_ID.",
    )
    parser.add_argument(
        "--codex-home",
        type=Path,
        default=Path(os.environ.get("CODEX_HOME", Path.home() / ".codex")),
        help=argparse.SUPPRESS,
    )
    return parser


def main(argv: Optional[Sequence[str]] = None) -> int:
    args = build_parser().parse_args(argv)
    session_id = args.session_id or os.environ.get("CODEX_THREAD_ID")
    print(render_sentence(args.codex_home.expanduser(), session_id))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
