from __future__ import annotations

import json
import os
from pathlib import Path
import subprocess
import sys
import tempfile
import unittest


REPO_ROOT = Path(__file__).resolve().parents[1]
SCRIPT = (
    REPO_ROOT
    / "personal_codex"
    / "skills"
    / "codex-session-mining"
    / "scripts"
    / "pr_attribution.py"
)
ROOT_SESSION = "11111111-1111-4111-8111-111111111111"
CHILD_SESSION = "22222222-2222-4222-8222-222222222222"
GRANDCHILD_SESSION = "33333333-3333-4333-8333-333333333333"
UNRELATED_SESSION = "44444444-4444-4444-8444-444444444444"
FALLBACK = (
    "This PR is purely generated by LLM: "
    "OpenAI Codex (GPT-5.6 Sol Ultra).\n"
)


def write_rollout(root: Path, session_id: str, rows: list[dict]) -> None:
    path = (
        root
        / "sessions"
        / "2026"
        / "08"
        / "11"
        / f"rollout-2026-08-11T12-00-00-{session_id}.jsonl"
    )
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        "".join(json.dumps(row, sort_keys=True) + "\n" for row in rows),
        encoding="utf-8",
    )


def turn(timestamp: str, turn_id: str, model: str, effort: str) -> dict:
    return {
        "timestamp": timestamp,
        "type": "turn_context",
        "payload": {
            "turn_id": turn_id,
            "model": model,
            "effort": effort,
        },
    }


def session_meta(timestamp: str, session_id: str, root_session_id: str) -> dict:
    return {
        "timestamp": timestamp,
        "type": "session_meta",
        "payload": {
            "id": session_id,
            "session_id": root_session_id,
        },
    }


def child(timestamp: str, session_id: str) -> dict:
    return {
        "timestamp": timestamp,
        "type": "event_msg",
        "payload": {
            "type": "sub_agent_activity",
            "agent_thread_id": session_id,
            "agent_path": "/root/example",
            "event_id": "event-1",
            "kind": "interrupted",
            "occurred_at_ms": 1786480000000,
        },
    }


class PrAttributionTests(unittest.TestCase):
    def run_helper(
        self,
        codex_home: Path,
        *arguments: str,
        session_id: str | None = ROOT_SESSION,
    ) -> str:
        environment = os.environ.copy()
        if session_id is None:
            environment.pop("CODEX_THREAD_ID", None)
        else:
            environment["CODEX_THREAD_ID"] = session_id
        result = subprocess.run(
            [
                sys.executable,
                str(SCRIPT),
                "--codex-home",
                str(codex_home),
                *arguments,
            ],
            check=False,
            capture_output=True,
            text=True,
            env=environment,
        )
        self.assertEqual(result.returncode, 0, result.stderr)
        self.assertEqual(result.stderr, "")
        return result.stdout

    def test_recursive_family_majority_deduplicates_turns(self) -> None:
        with tempfile.TemporaryDirectory() as temporary_directory:
            codex_home = Path(temporary_directory)
            write_rollout(
                codex_home,
                ROOT_SESSION,
                [
                    session_meta("2026-08-11T11:59:59Z", ROOT_SESSION, ROOT_SESSION),
                    turn("2026-08-11T12:00:00Z", "root-a", "gpt-5.6-sol", "max"),
                    turn("2026-08-11T12:00:10Z", "root-a", "gpt-5.6-sol", "max"),
                    turn("2026-08-11T12:00:20Z", "root-a", "gpt-5.6-sol", "max"),
                    turn("2026-08-11T12:00:30Z", "root-a", "gpt-5.6-sol", "max"),
                    turn("2026-08-11T12:01:00.490Z", "root-a", "gpt-5.6-sol", "xhigh"),
                    turn("2026-08-11T12:02:00Z", "root-b", "gpt-5.6-sol", "max"),
                    child("2026-08-11T12:03:00Z", CHILD_SESSION),
                ],
            )
            write_rollout(
                codex_home,
                CHILD_SESSION,
                [
                    session_meta("2026-08-11T12:03:30Z", CHILD_SESSION, ROOT_SESSION),
                    turn("2026-08-11T12:04:00Z", "child-a", "gpt-5.6-sol", "xhigh"),
                    turn("2026-08-11T12:04:30Z", "child-b", "gpt-5.6-sol", "max"),
                    child("2026-08-11T12:05:00Z", GRANDCHILD_SESSION),
                ],
            )
            write_rollout(
                codex_home,
                GRANDCHILD_SESSION,
                [
                    session_meta(
                        "2026-08-11T12:05:30Z",
                        GRANDCHILD_SESSION,
                        ROOT_SESSION,
                    ),
                    turn(
                        "2026-08-11T12:06:00Z",
                        "grandchild-a",
                        "gpt-5.6-sol",
                        "xhigh",
                    ),
                ],
            )

            expected = (
                "This PR is purely generated by LLM: "
                "OpenAI Codex (GPT-5.6 Sol Extra High).\n"
            )
            self.assertEqual(self.run_helper(codex_home), expected)

    def test_child_selector_resolves_desktop_root(self) -> None:
        with tempfile.TemporaryDirectory() as temporary_directory:
            codex_home = Path(temporary_directory)
            write_rollout(
                codex_home,
                ROOT_SESSION,
                [
                    session_meta("2026-08-11T12:00:00Z", ROOT_SESSION, ROOT_SESSION),
                    turn("2026-08-11T12:01:00Z", "root-a", "gpt-5.6-sol", "xhigh"),
                    turn("2026-08-11T12:02:00Z", "root-b", "gpt-5.6-sol", "xhigh"),
                    turn("2026-08-11T12:03:00Z", "root-c", "gpt-5.6-sol", "xhigh"),
                    turn("2026-08-11T12:04:00Z", "root-d", "gpt-5.6-sol", "xhigh"),
                    child("2026-08-11T12:05:00Z", CHILD_SESSION),
                ],
            )
            write_rollout(
                codex_home,
                CHILD_SESSION,
                [
                    session_meta("2026-08-11T12:05:30Z", CHILD_SESSION, ROOT_SESSION),
                    turn("2026-08-11T12:06:00Z", "child-a", "gpt-5.6-sol", "max"),
                    turn("2026-08-11T12:07:00Z", "child-b", "gpt-5.6-sol", "max"),
                    turn("2026-08-11T12:08:00Z", "child-c", "gpt-5.6-sol", "max"),
                ],
            )

            self.assertEqual(
                self.run_helper(
                    codex_home,
                    "--session-id",
                    CHILD_SESSION,
                    session_id="44444444-4444-4444-8444-444444444444",
                ),
                "This PR is purely generated by LLM: "
                "OpenAI Codex (GPT-5.6 Sol Extra High).\n",
            )

    def test_latest_pair_breaks_ties(self) -> None:
        with tempfile.TemporaryDirectory() as temporary_directory:
            codex_home = Path(temporary_directory)
            write_rollout(
                codex_home,
                ROOT_SESSION,
                [
                    turn(
                        "2026-08-11T15:00:00Z",
                        "019ff116-ddd1-72f2-bff7-8a0d997c4b66",
                        "gpt-5.6-sol",
                        "xhigh",
                    ),
                    turn(
                        "2026-08-11T14:00:00Z",
                        "019ff16a-1f1d-7eb1-a384-2ded9a4e86cb",
                        "gpt-5.6-sol",
                        "max",
                    ),
                ],
            )

            self.assertEqual(
                self.run_helper(codex_home),
                "This PR is purely generated by LLM: "
                "OpenAI Codex (GPT-5.6 Sol Max).\n",
            )

    def test_same_millisecond_tie_uses_full_fallback(self) -> None:
        with tempfile.TemporaryDirectory() as temporary_directory:
            codex_home = Path(temporary_directory)
            write_rollout(
                codex_home,
                ROOT_SESSION,
                [
                    turn(
                        "2026-08-11T15:00:00Z",
                        "019ff116-ddd1-72f2-bff7-8a0d997c4b66",
                        "gpt-5.6-sol",
                        "xhigh",
                    ),
                    turn(
                        "2026-08-11T14:00:00Z",
                        "019ff116-ddd1-7fff-8fff-ffffffffffff",
                        "gpt-5.6-sol",
                        "max",
                    ),
                ],
            )

            self.assertEqual(self.run_helper(codex_home), FALLBACK)

    def test_non_uuidv7_tie_uses_full_fallback(self) -> None:
        with tempfile.TemporaryDirectory() as temporary_directory:
            codex_home = Path(temporary_directory)
            write_rollout(
                codex_home,
                ROOT_SESSION,
                [
                    turn("2026-08-11T12:00:00Z", "turn-a", "gpt-5.6-sol", "xhigh"),
                    turn("2026-08-11T12:01:00Z", "turn-b", "gpt-5.6-sol", "max"),
                ],
            )

            self.assertEqual(self.run_helper(codex_home), FALLBACK)

    def test_turn_ids_are_deduplicated_per_session(self) -> None:
        with tempfile.TemporaryDirectory() as temporary_directory:
            codex_home = Path(temporary_directory)
            shared_turn_id = "019ff116-ddd1-72f2-bff7-8a0d997c4b66"
            write_rollout(
                codex_home,
                ROOT_SESSION,
                [
                    turn("2026-08-11T12:00:00Z", shared_turn_id, "gpt-5.6-sol", "max"),
                    turn(
                        "2026-08-11T12:01:00Z",
                        "019ff16a-1f1d-7eb1-a384-2ded9a4e86cb",
                        "gpt-5.6-sol",
                        "xhigh",
                    ),
                    child("2026-08-11T12:02:00Z", CHILD_SESSION),
                ],
            )
            write_rollout(
                codex_home,
                CHILD_SESSION,
                [
                    session_meta("2026-08-11T12:02:30Z", CHILD_SESSION, ROOT_SESSION),
                    turn(
                        "2026-08-11T12:03:00Z",
                        shared_turn_id,
                        "gpt-5.6-sol",
                        "max",
                    ),
                ],
            )

            self.assertEqual(
                self.run_helper(codex_home),
                "This PR is purely generated by LLM: "
                "OpenAI Codex (GPT-5.6 Sol Max).\n",
            )

    def test_same_turn_identity_with_different_pairs_uses_full_fallback(self) -> None:
        with tempfile.TemporaryDirectory() as temporary_directory:
            codex_home = Path(temporary_directory)
            shared_turn_id = "019ff116-ddd1-72f2-bff7-8a0d997c4b66"
            write_rollout(
                codex_home,
                ROOT_SESSION,
                [
                    turn("2026-08-11T12:00:00Z", shared_turn_id, "gpt-5.6-sol", "max"),
                    child("2026-08-11T12:01:00Z", CHILD_SESSION),
                ],
            )
            write_rollout(
                codex_home,
                CHILD_SESSION,
                [
                    session_meta("2026-08-11T12:01:30Z", CHILD_SESSION, ROOT_SESSION),
                    turn(
                        "2026-08-11T12:02:00Z",
                        shared_turn_id,
                        "gpt-5.6-sol",
                        "xhigh",
                    ),
                ],
            )

            self.assertEqual(self.run_helper(codex_home), FALLBACK)

    def test_desktop_effort_labels(self) -> None:
        labels = {
            "low": "Low",
            "medium": "Medium",
            "high": "High",
            "xhigh": "Extra High",
            "max": "Max",
            "ultra": "Ultra",
        }
        for effort, label in labels.items():
            with (
                self.subTest(effort=effort),
                tempfile.TemporaryDirectory() as temporary_directory,
            ):
                codex_home = Path(temporary_directory)
                write_rollout(
                    codex_home,
                    ROOT_SESSION,
                    [turn("2026-08-11T12:00:00Z", "root-a", "gpt-5.6-sol", effort)],
                )

                self.assertEqual(
                    self.run_helper(codex_home),
                    "This PR is purely generated by LLM: "
                    f"OpenAI Codex (GPT-5.6 Sol {label}).\n",
                )

    def test_unknown_winning_pair_uses_full_fallback(self) -> None:
        with tempfile.TemporaryDirectory() as temporary_directory:
            codex_home = Path(temporary_directory)
            write_rollout(
                codex_home,
                ROOT_SESSION,
                [turn("2026-08-11T12:00:00Z", "root-a", "future-model", "ultra")],
            )

            self.assertEqual(self.run_helper(codex_home), FALLBACK)

    def test_missing_exact_session_uses_full_fallback(self) -> None:
        with tempfile.TemporaryDirectory() as temporary_directory:
            codex_home = Path(temporary_directory)
            write_rollout(
                codex_home,
                ROOT_SESSION,
                [turn("2026-08-11T12:00:00Z", "root-a", "gpt-5.6-sol", "max")],
            )
            self.assertEqual(
                self.run_helper(codex_home, session_id=UNRELATED_SESSION),
                FALLBACK,
            )

    def test_malformed_selected_rollout_uses_full_fallback(self) -> None:
        with tempfile.TemporaryDirectory() as temporary_directory:
            codex_home = Path(temporary_directory)
            write_rollout(
                codex_home,
                ROOT_SESSION,
                [turn("2026-08-11T12:00:00Z", "root-a", "gpt-5.6-sol", "max")],
            )
            rollout = next((codex_home / "sessions").rglob("*.jsonl"))
            with rollout.open("a", encoding="utf-8") as handle:
                handle.write("{malformed}\n")

            self.assertEqual(self.run_helper(codex_home), FALLBACK)

    def test_non_object_selected_record_uses_full_fallback(self) -> None:
        with tempfile.TemporaryDirectory() as temporary_directory:
            codex_home = Path(temporary_directory)
            write_rollout(
                codex_home,
                ROOT_SESSION,
                [turn("2026-08-11T12:00:00Z", "root-a", "gpt-5.6-sol", "max")],
            )
            rollout = next((codex_home / "sessions").rglob("*.jsonl"))
            with rollout.open("a", encoding="utf-8") as handle:
                handle.write("[]\n")

            self.assertEqual(self.run_helper(codex_home), FALLBACK)

    def test_invalid_relevant_payload_uses_full_fallback(self) -> None:
        with tempfile.TemporaryDirectory() as temporary_directory:
            codex_home = Path(temporary_directory)
            write_rollout(
                codex_home,
                ROOT_SESSION,
                [turn("2026-08-11T12:00:00Z", "root-a", "gpt-5.6-sol", "max")],
            )
            rollout = next((codex_home / "sessions").rglob("*.jsonl"))
            with rollout.open("a", encoding="utf-8") as handle:
                handle.write(
                    json.dumps({"type": "turn_context", "payload": []}) + "\n"
                )

            self.assertEqual(self.run_helper(codex_home), FALLBACK)

    def test_missing_referenced_subagent_uses_full_fallback(self) -> None:
        with tempfile.TemporaryDirectory() as temporary_directory:
            codex_home = Path(temporary_directory)
            write_rollout(
                codex_home,
                ROOT_SESSION,
                [
                    turn("2026-08-11T12:00:00Z", "root-a", "gpt-5.6-sol", "max"),
                    child("2026-08-11T12:01:00Z", CHILD_SESSION),
                ],
            )

            self.assertEqual(self.run_helper(codex_home), FALLBACK)

    def test_personal_guidance_routes_pr_note_to_helper(self) -> None:
        agents = (REPO_ROOT / "personal_codex" / "AGENTS.md").read_text(
            encoding="utf-8"
        )
        skill = (
            REPO_ROOT / "personal_codex" / "skills" / "codex-session-mining" / "SKILL.md"
        ).read_text(encoding="utf-8")

        self.assertIn("scripts/pr_attribution.py", agents)
        self.assertIn("immediately before merge", agents)
        self.assertIn("GPT-5.6 Sol Ultra", agents)
        self.assertNotIn("summaries auto", agents)
        self.assertIn("## PR Attribution", skill)


if __name__ == "__main__":
    unittest.main()
